import sqlite3
import pandas as pd

DB_NAME = "music_store.db"

def get_db_connection():
    conn = sqlite3.connect(DB_NAME)
    return conn

def get_schema_representation():
    """
    Fetches table names and columns to give context to the AI.
    Interview Win: Explain that this makes your bot 'Dynamic' and not hard-coded.
    """
    conn = get_db_connection()
    cursor = conn.cursor()
    
    # Get all table names
    cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
    tables = cursor.fetchall()
    
    schema_str = ""
    for table in tables:
        table_name = table[0]
        cursor.execute(f"PRAGMA table_info({table_name})")
        columns = cursor.fetchall()
        column_names = [col[1] for col in columns]
        schema_str += f"Table: {table_name}, Columns: {', '.join(column_names)}\n"
        
    conn.close()
    return schema_str

def execute_query(sql_query):
    """Executes the SQL generated by the AI."""
    conn = get_db_connection()
    try:
        # Using Pandas here makes it easier to format results for Slack
        df = pd.read_sql_query(sql_query, conn)
        conn.close()
        return df
    except Exception as e:
        conn.close()
        return f"Error executing SQL: {e}"